### ISSUE TITLE
Don't recreate the wheel!

### ISSUE THREAD

**Issue by luissilva1044894** [ErnestoAlvarado/Paladins_API#1]
If you just want to use `Paladins API` and the purpose isn't to study Hi-Rez APIs/writing your own wrapper, there are already 3 wrappers for Python: [Pyrez](https://github.com/luissilva1044894/Pyrez), [HiRezAPI](https://github.com/DevilXD/HiRezAPI), [Hi-RezAPI](https://github.com/iforvard/Hi-RezAPI).

I've listed some of them [here](https://github.com/luissilva1044894/hirez-api-docs#wrappers).

**Comment by ErnestoAlvarado** [comment]
Hi, thank you for the suggestions, but I'm currently writing my own wrapper for leaning purposes.
